package:
  name: ros-humble-rviz-default-plugins
  version: 11.2.2
source:
  git_url: https://github.com/ros2-gbp/rviz-release.git
  git_rev: release/humble/rviz_default_plugins/11.2.2-1
  folder: ros-humble-rviz-default-plugins/src/work
  patches:
    - patch/ros-humble-rviz-default-plugins.patch

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - python
    - qt-main
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gmock
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-ament-cmake-xmllint
    - ros-humble-ament-index-cpp
    - ros-humble-ament-lint-auto
    - ros-humble-geometry-msgs
    - ros-humble-ignition-math6-vendor
    - ros-humble-image-transport
    - ros-humble-interactive-markers
    - ros-humble-laser-geometry
    - ros-humble-map-msgs
    - ros-humble-nav-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-resource-retriever
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-rviz-common
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-rviz-rendering-tests
    - ros-humble-rviz-visual-testing-framework
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - qt-main
    - ros-humble-geometry-msgs
    - ros-humble-ignition-math6-vendor
    - ros-humble-image-transport
    - ros-humble-interactive-markers
    - ros-humble-laser-geometry
    - ros-humble-map-msgs
    - ros-humble-nav-msgs
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-resource-retriever
    - ros-humble-ros-workspace
    - ros-humble-rviz-common
    - ros-humble-rviz-ogre-vendor
    - ros-humble-rviz-rendering
    - ros-humble-tf2
    - ros-humble-tf2-geometry-msgs
    - ros-humble-tf2-ros
    - ros-humble-urdf
    - ros-humble-visualization-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
