package:
  name: ros-humble-laser-geometry
  version: 2.4.0
source:
  git_url: https://github.com/ros2-gbp/laser_geometry-release.git
  git_rev: release/humble/laser_geometry/2.4.0-2
  folder: ros-humble-laser-geometry/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-lint-cmake
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-eigen3-cmake-module
    - ros-humble-python-cmake-module
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-tf2
    - ros2-distro-mutex 0.1 humble
  run:
    - eigen
    - numpy
    - python
    - ros-humble-eigen3-cmake-module
    - ros-humble-rclcpp
    - ros-humble-rclpy
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-sensor-msgs-py
    - ros-humble-tf2
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
