package:
  name: ros-humble-rqt-topic
  version: 1.2.3
source:
  git_url: https://github.com/ros2-gbp/rqt_topic-release.git
  git_rev: release/humble/rqt_topic/1.2.3-2
  folder: ros-humble-rqt-topic/src/work

build:
  script:
    sel(win): bld_ament_python.bat
    sel(unix): build_ament_python.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-humble-ament-flake8
    - ros-humble-ament-xmllint
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - setuptools
  run:
    - python
    - ros-humble-python-qt-binding
    - ros-humble-ros-workspace
    - ros-humble-rqt-gui
    - ros-humble-rqt-gui-py
    - ros-humble-rqt-py-common
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
