package:
  name: ros-humble-intra-process-demo
  version: 0.20.2
source:
  git_url: https://github.com/ros2-gbp/demos-release.git
  git_rev: release/humble/intra_process_demo/0.20.2-1
  folder: ros-humble-intra-process-demo/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(linux): "{{ cdt('mesa-libgl-devel') }}"
    - sel(linux): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - libopencv
    - py-opencv
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-pytest
    - ros-humble-ament-lint-auto
    - ros-humble-ament-lint-common
    - ros-humble-launch
    - ros-humble-launch-testing
    - ros-humble-launch-testing-ament-cmake
    - ros-humble-rclcpp
    - ros-humble-rmw-implementation-cmake
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros-humble-std-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - libopencv
    - py-opencv
    - python
    - ros-humble-rclcpp
    - ros-humble-ros-workspace
    - ros-humble-sensor-msgs
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
