package:
  name: ros-humble-filters
  version: 2.1.0
source:
  git_url: https://github.com/ros2-gbp/filters-release.git
  git_rev: release/humble/filters/2.1.0-3
  folder: ros-humble-filters/src/work

build:
  script:
    sel(win): bld_ament_cmake.bat
    sel(unix): build_ament_cmake.sh
  number: 0
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost-cpp
    - python
    - ros-humble-ament-cmake
    - ros-humble-ament-cmake-cppcheck
    - ros-humble-ament-cmake-cpplint
    - ros-humble-ament-cmake-gtest
    - ros-humble-ament-cmake-uncrustify
    - ros-humble-ament-cmake-xmllint
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-ros-environment
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
  run:
    - boost-cpp
    - python
    - ros-humble-pluginlib
    - ros-humble-rclcpp
    - ros-humble-ros-workspace
    - ros2-distro-mutex 0.1 humble
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
